import { z } from "zod";

import { extractYouTubeId, extractYouTubePlaylistId, isAutoGeneratedPlaylistId } from "@/lib/youtube";

export const addSongSchema = z.object({
  youtubeUrl: z
    .string()
    .min(1, "YouTube linki zorunlu")
    .refine(
      (url) => extractYouTubeId(url) !== null || extractYouTubePlaylistId(url) !== null,
      "Geçerli bir YouTube linki girin",
    )
    .refine(
      (url) => {
        const playlistId = extractYouTubePlaylistId(url);
        // Playlist kısmı yoksa veya video linkiyle birlikteyse (o zaman tek
        // şarkı eklenir, playlist kısmı yok sayılır) sorun değil — sadece
        // link TEK BAŞINA desteklenmeyen bir playlist'e işaret ediyorsa engelle.
        if (!playlistId || extractYouTubeId(url)) return true;
        return !isAutoGeneratedPlaylistId(playlistId);
      },
      "Bu, YouTube'un otomatik oluşturduğu bir karışık/radyo listesi (\"RD\" ile başlar) — istek anında izlediğiniz videoya ve hesabınıza göre dinamik oluşturulduğu için içeri aktarılamıyor. Sadece kullanıcı oynatma listeleri (\"PL\" ile başlayan) eklenebilir.",
    ),
});

export type AddSongFormValues = z.infer<typeof addSongSchema>;
