"use client";

import {
  Button,
  Checkbox,
  Description,
  FieldError,
  Form,
  Input,
  Label,
  Modal,
  TextField,
  useOverlayState,
} from "@heroui/react";
import { zodResolver } from "@hookform/resolvers/zod";
import { Plus } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";
import { Controller, useForm, useWatch } from "react-hook-form";

import { getErrorMessage } from "@/api/client";
import { useAddTrack } from "@/features/playlist/hooks/useAddTrack";
import { addSongSchema, type AddSongFormValues } from "@/features/playlist/schemas/add-song-schema";
import { extractYouTubeId, extractYouTubePlaylistId, isAutoGeneratedPlaylistId } from "@/lib/youtube";

export function AddSongForm() {
  const state = useOverlayState();
  const addSongMutation = useAddTrack();
  const [addFullPlaylist, setAddFullPlaylist] = useState(false);

  const {
    control,
    handleSubmit,
    setError,
    reset,
    formState: { errors },
  } = useForm<AddSongFormValues>({
    resolver: zodResolver(addSongSchema),
    defaultValues: { youtubeUrl: "" },
  });

  const youtubeUrl = useWatch({ control, name: "youtubeUrl" });
  const videoId = extractYouTubeId(youtubeUrl);
  const rawPlaylistId = extractYouTubePlaylistId(youtubeUrl);
  // "RD" ile başlayan karışık/radyo listeleri desteklenmiyor (bkz.
  // add-song-schema) — video linkiyle birlikte geldiyse sessizce yok
  // sayılır (video eklenir), checkbox da gösterilmez.
  const playlistId = rawPlaylistId && !isAutoGeneratedPlaylistId(rawPlaylistId) ? rawPlaylistId : null;
  // Link hem tek şarkıya hem playlist'e işaret ediyorsa (ör.
  // ?v=...&list=...) kullanıcı hangisini istediğini seçer; sadece playlist
  // linkiyse (video id yok) zaten tüm liste eklenir, seçim gerekmez.
  const showPlaylistCheckbox = Boolean(videoId && playlistId);

  function onOpenChange(open: boolean) {
    state.setOpen(open);
    if (!open) {
      reset();
      setAddFullPlaylist(false);
    }
  }

  function onSubmit(values: AddSongFormValues) {
    const mode = playlistId && (!videoId || addFullPlaylist) ? "playlist" : videoId ? "video" : undefined;
    const isPlaylistImport = mode === "playlist";

    addSongMutation.mutate(
      { youtubeUrl: values.youtubeUrl, mode },
      {
        onSuccess: () => {
          reset();
          setAddFullPlaylist(false);
          if (!isPlaylistImport) state.close();
        },
        onError: (error) => {
          if (!isPlaylistImport) setError("youtubeUrl", { message: getErrorMessage(error) });
        },
      },
    );

    // Playlist importu uzun sürebilir (bkz. useAddTrack); kullanıcıyı modal
    // açık bekletmek yerine hemen kapatıyoruz — ilerleme tablonun üstünde
    // (bkz. PlaylistTable) gösterilir, sonuç toast ile bildirilir.
    if (isPlaylistImport) {
      reset();
      setAddFullPlaylist(false);
      state.close();
    }
  }

  return (
    <>
      <Button size="sm" variant="primary" onPress={state.open}>
        <Plus className="size-4" />
        Şarkı ekle
      </Button>

      <Modal.Backdrop isOpen={state.isOpen} onOpenChange={onOpenChange}>
        <Modal.Container>
          <Modal.Dialog className="sm:max-w-md">
            <Modal.CloseTrigger />
            <Modal.Header>
              <Modal.Heading>Şarkı ekle</Modal.Heading>
            </Modal.Header>
            <Form onSubmit={handleSubmit(onSubmit)}>
              <Modal.Body>
                <Controller
                  control={control}
                  name="youtubeUrl"
                  render={({ field }) => (
                    <TextField
                      className="w-full"
                      isInvalid={!!errors.youtubeUrl}
                      isRequired
                      name={field.name}
                      value={field.value}
                      onBlur={field.onBlur}
                      onChange={field.onChange}
                    >
                      <Label>YouTube linki</Label>
                      <Input placeholder="https://www.youtube.com/watch?v=dQw4w9WgXcQ" />
                      {errors.youtubeUrl ? (
                        <FieldError>{errors.youtubeUrl.message}</FieldError>
                      ) : (
                        <Description>Eklemek istediğiniz şarkı veya oynatma listesinin URL&apos;sini girin.</Description>
                      )}
                    </TextField>
                  )}
                />
                <AnimatePresence initial={false}>
                  {showPlaylistCheckbox ? (
                    <motion.div
                      key="playlist-checkbox"
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.2 }}
                      className="overflow-hidden"
                    >
                      <Checkbox className="pt-2" isSelected={addFullPlaylist} onChange={setAddFullPlaylist}>
                        <Checkbox.Content>
                          <Checkbox.Control>
                            <Checkbox.Indicator />
                          </Checkbox.Control>
                          Bu oynatma listesindeki şarkıların hepsini ekle
                        </Checkbox.Content>
                      </Checkbox>
                    </motion.div>
                  ) : null}
                </AnimatePresence>
              </Modal.Body>
              <Modal.Footer>
                <Button slot="close" variant="secondary">
                  Vazgeç
                </Button>
                <Button isDisabled={addSongMutation.isPending} type="submit" variant="primary">
                  {addSongMutation.isPending ? "Ekleniyor..." : "Ekle"}
                </Button>
              </Modal.Footer>
            </Form>
          </Modal.Dialog>
        </Modal.Container>
      </Modal.Backdrop>
    </>
  );
}
