const YOUTUBE_ID_PATTERN = /^[a-zA-Z0-9_-]{11}$/;
const PLAYLIST_ID_PATTERN = /^[a-zA-Z0-9_-]{13,}$/;
// YouTube'un otomatik oluşturduğu karışık/radyo listeleri ("RD" ile
// başlayan) istek anında, o an izlenen videoya ve kullanıcıya göre dinamik
// üretilir — sabit bir içeriği yoktur, bu yüzden backend bunları import
// etmiyor (bkz. youtube.Client.FetchPlaylistItems).
const AUTO_PLAYLIST_PREFIX = "RD";

export function extractYouTubeId(input: string): string | null {
  const trimmed = input.trim();
  if (YOUTUBE_ID_PATTERN.test(trimmed)) return trimmed;

  try {
    const url = new URL(trimmed);
    const vParam = url.searchParams.get("v");
    if (vParam && YOUTUBE_ID_PATTERN.test(vParam)) return vParam;

    if (url.hostname === "youtu.be") {
      const id = url.pathname.slice(1);
      if (YOUTUBE_ID_PATTERN.test(id)) return id;
    }
  } catch {
    return null;
  }

  return null;
}

// Playlist linki hem tek bir video linkinde (`/watch?v=...&list=...`) hem de
// doğrudan bir playlist linkinde (`/playlist?list=...`) gelebilir — hangisi
// olduğu path'ten değil, kullanıcının seçtiği moddan (bkz. AddSongForm) belli
// olur.
export function extractYouTubePlaylistId(input: string): string | null {
  const trimmed = input.trim();

  try {
    const url = new URL(trimmed);
    const listParam = url.searchParams.get("list");
    if (listParam && PLAYLIST_ID_PATTERN.test(listParam)) return listParam;
  } catch {
    return null;
  }

  return null;
}

// isAutoGeneratedPlaylistId, verilen playlist ID'sinin YouTube'un otomatik
// karışık/radyo listesi olup olmadığını söyler (bkz. AUTO_PLAYLIST_PREFIX).
export function isAutoGeneratedPlaylistId(playlistId: string): boolean {
  return playlistId.startsWith(AUTO_PLAYLIST_PREFIX);
}
